### ISSUE TITLE
User Story 7:Browsing for available job postings

### ISSUE THREAD

**Issue by laurenrigante** [F4KER-X/TalentVault-SOEN-341-Project-2023#23]
As an applicant seeking a job, I want to be able to browse through available job postings so I can find a job relevant to me and my needs.

Tasks:

- [Design the UI for the job browsing page](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/55)
- [Design job component](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/56)
- [Create the job model](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/57)
- [Create the job API](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/58)
- [Connect frontend and backend](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/59)
- [Add search and filtering functionality](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/60)
- [Pagination](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/61)
- [Add authentication and authorization](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/62)

**Comment by Itek01** [comment]
AT – 1.1 Browsing through Job Postings
This acceptance is for User Story #23

**User Acceptance Flow** 
1.	User browses through a list of all available job postings on the system for each job posting in the list. 
2.	User as an applicant clicks on a job posting to view its full details, including job title, city location, and position length.
3.	User can navigate through different pages of these postings.
a.	Once he’s on the following pages, he can go back to the earlier ones.

**Comment by F4KER-X** [comment]
AT- 7.2: Pagination

**User Acceptance Flow**

1. User tries to other browsing pages 
2. Different jobs are displayed ( no duplicates )
3. User is able to find the same functionalities as other pages.

**Comment by F4KER-X** [comment]
AT - 7.3: User role

**User Acceptance Flow**

1. If user is an application, user can't see the add job button, or can't make any modification
2. If user is a recruiter, user is able to add a new job, delete user's jobs or edit
