### ISSUE TITLE
User Story 6: Adding and managing postings to the system by the employers

### ISSUE THREAD

**Issue by despinakouli** [F4KER-X/TalentVault-SOEN-341-Project-2023#24]
As an employer, I want to be able to create and edit detailed job postings on the system so the applicants can find a job that satisfies their needs. I also want to be able to delete a job posting once it has been filled, so that i do not receive applications for closed jobs.
Possible job details

- Job title
- Company name
- Max salary
- Min salary
- Job description
- Job type
- Job requirements
- Job location
- Job open date

Tasks:

- [Design the UI for the job posting and management page](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/48)
- [Create a Job model](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/49)
- [Create the job API](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/50)
- [Connect frontend and backend](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/51)
- [Add editing and deleting functionality](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/52)
- [Ensure security for jobs](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/53)
- [Add authentication and authorization](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/54)

**Comment by F4KER-X** [comment]
AT - 6.1: Add job

**User Acceptance Flow**

1. User clicks to add a job
2. User fills out all fields
3. User clicks save
4. Data is sent to the database
5. Job is added

**Comment by F4KER-X** [comment]
AT - 6.2: Update job

**User Acceptance Flow**

1. User chooses one the jobs to update
2. User changes some information
3. User save the job
4. Data is updated in the database

**Comment by F4KER-X** [comment]
AT - 6.3: Delete job

User Acceptance Flow

1. User chooses one job to delete
2. User gets promoted to confirm the deletion 
3. Job is deleted from the database
