### ISSUE TITLE
User Story 8: Applicants are notified if they are selected for an interview

### ISSUE THREAD

**Issue by laurenrigante** [F4KER-X/TalentVault-SOEN-341-Project-2023#27]
As a user , I want to receive a notification from the system  if I was selected for an interview

Tasks:

- [Build Email notification functionality](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/63)
- [Send an email to the applicant if their applicant got selected for an interview](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/65)

**Comment by F4KER-X** [comment]
AT - 8.1: Recruiter notification

**User Acceptance Flow**

- Applicant applies to a new job
- Applicant is accepted and saved 
- System sends a notification by email to the recruiter to let them know

**Comment by F4KER-X** [comment]
AT - 8.2: Applicant notification

**User Acceptance Flow**

- Recruiter selects an application for an interview
- The applicant is notified by email
