### ISSUE TITLE
User Story 1: Registration Page

### ISSUE THREAD

**Issue by JXOXO** [F4KER-X/TalentVault-SOEN-341-Project-2023#3]
As a new user, I want to create an account and fill my information in the registration page, so I can save my personal info to be seen by companies.

Include:
- First Name
- Last Name
- Email Address
- Password
- Confirm Password
- Sign in Link

Tasks:

- [Create UI for the registration page](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/29)
- [Make POST requests to the backend to save the data in the database
](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/31)
- [Handle frontend errors such as invalid email, wrong password or empty fields](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/32)
- [Create backend functionality](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/33)
- [Connect the frontend to backend](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/34)
- [Add error handling](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/35)
- [Add success messaging](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/36)
- [Password security](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/new)
- [JWT and authentication](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/38)

**Comment by F4KER-X** [comment]
AT - 1.1: Sign up:

**User Acceptance Flow** 

1. User enters valid data and unused email address
2. User clicks on Sign up button
3. Data is sent to the database and a success message is displayed
4. User is directed to the next page

**Comment by F4KER-X** [comment]
AT - 1.2: Sign up

**User Acceptance Flow**

1. User enters already used email
2. User clicks on Sign up button
3. Error is displayed for the user to change the email
4. Data is not saved and no redirection happens

**Comment by F4KER-X** [comment]
AT 1.3: Sign up V3

**User Acceptance Flow**

1. User leaves some fields empty
2. User clicks on Sign up button
3. Error is displayed to the user to fill out the remaining fields
4. No HTTP request is made and no redirection happens

**Comment by F4KER-X** [comment]
AT - 1.4: Sign up V4

**User Acceptance Flow**

1. User fills out the password and confirm password fields
2. System compare both fields
3. Fields do not match 
4. Error displayed for the user to confirm the passwords
5. No request is made and no redirection.
