### ISSUE TITLE
User Story 2: Login Page

### ISSUE THREAD

**Issue by JXOXO** [F4KER-X/TalentVault-SOEN-341-Project-2023#4]
As a registered user, I want the login page simple with a forget password option, so I can change the password just incase. 

includes:
- Email
- Password
- Forget Password
- Link to registration Page

Tasks:

- [Create the UI for the login page](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/28)
- [Set up validation](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/39)
- [Implement backend functionality](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/40)
- [Add error handling](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/41)
- [Add success messaging](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/42)
- [JWT and security](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/43)

**Comment by F4KER-X** [comment]
AT - 2.1: Login V1

**User Acceptance Flow**

1. User enters a valid email and password
2. System checks the database for a match 
3. Email is found, system compare passwords 
4. System send a OK response
5. User is logged in and redirected

**Comment by F4KER-X** [comment]
AT - 2.2: Login V1

**User Acceptance Flow**

1. User enters email and password 
2. System checks the database for a match 
3. Email or password do not match
4. Error is displayed for the user to check the inputs
5. No redirection is made

**Comment by F4KER-X** [comment]
AT - 2.3: Login V3

**User Acceptance Flow**

1. User clicks on the Signup button
2. User is redirected to the registration page

**Comment by F4KER-X** [comment]
AT - 2.4: Login V3

**User Acceptance Flow**

1. User clicks the Forgot password button
2. User is redirected to the forgot password page
