### ISSUE TITLE
User Story 3: Job Description

### ISSUE THREAD

**Issue by JXOXO** [F4KER-X/TalentVault-SOEN-341-Project-2023#5]
As a registered user, I want to be able to see a full description of a job, so I can get a full understanding of the companies offers. 

Includes:
- Min/Max salary
- Job type
- Job title
- Company Name
- Job description 
- Requirements 
- Location

Story points: 6 
Reason: 

Tasks:

Frontend:

- Create a job component including the mentions information above
- Create a job page model for each job
- Make a POST request to the backend to save the job to the database
- Handle any frontend errors if any fields are left empty
- clicking on the job directs the user to another page that display more information about the job
- add Apply now button to let the user apply for the specific job

Backend:

- Create a POST endpoint to add jobs 
- Create POST endpoint to allow applicants to apply for a specific job 
- Create a GET endpoint to get all jobs and another GET endpoint to get a specific job by Id
- Create a PATCH endpoint to update a specific job details
- Create a DELETE endpoint to allow recruiter to delete the jobs if the status of the jobs is closed
- Validate all data entered to the database before saving 

Acceptance tests:

1. When a GET request to get all jobs is sent to the backend -> backend should respond with every single job saved
2. Creating a job will send a POST request to the backend -> if request is successful, then the job is saved 
3. Delete request while having an application -> Backend should respond with an error 
4. Clicking on any job -> User directed to a specific page that has more info about the job.

Risks:

**Comment by F4KER-X** [comment]
Case closed as it's been moved to #23
