### ISSUE TITLE
Backend Graphical Design needed for continuity

### ISSUE THREAD

**Issue by Itek01** [F4KER-X/TalentVault-SOEN-341-Project-2023#7]
#### Since we're just starting the project, we're having problems decide the backend format of the project

*@F4KER-X Already talked about possibly using the node/express/mongo framework*

We'd need some kind of UML diagram to put the whole team on the same page

**Comment by F4KER-X** [comment]
Looking for UML diagram for the relationship between the mongoDB

**Comment by F4KER-X** [comment]
Issue closed. DB design is decided and implemented for most of the parts.
