### ISSUE TITLE
User Story 9: Applicants are able to apply for a job and view their own applications

### ISSUE THREAD

**Issue by F4KER-X** [F4KER-X/TalentVault-SOEN-341-Project-2023#76]
As an applicant, I want to be able to submit an application for a specific job. I also would like to be able to view the status of my applications

Tasks:

- [Applicants are able to apply for a job](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/73)
- [Applicants are able view all their applications' status](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/74)
- [Recruiters are able to change the status of the applications](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/75)

**Comment by despinakouli** [comment]
AT - 9.1 Applicants apply for a job

**User Acceptance Flow**

1. User browses through available job postings
2. User as an applicant chooses a posting and clicks on the more info button
3. User can view details about the job (job type, salary, requirements, description, location, full-time or part time, remote or onsite)
4. User clicks on apply button and the job is sent to their applications list

**Comment by despinakouli** [comment]
AT - 9.2 Applicants view their application status

**User Acceptance Flow**

1. User as an applicant click on their top left profile page and clicks on "My applications"
2. User is redirected to a page listing all their job applications
3. User can view the status of their application

**Comment by despinakouli** [comment]
AT - 9.3 Recruiters edits status of applications

**User Acceptance Flow**

1. User as a recruiter clicks on their top left profile picture and clicks on "My jobs"
2. User is redirected to a page listing all their jobs
3. User can change the status of the applications
