### ISSUE TITLE
Front-end design to get started

### ISSUE THREAD

**Issue by Itek01** [F4KER-X/TalentVault-SOEN-341-Project-2023#8]
We'd need some kind of UML diagram to put the whole team on the same page
We don't have a proper graphical designer on the team.

@Alinoureddine1 volunteered to try out designs on figma, but he's gonna need assistance

We need to have it ready as soon as possible so the front-end team can begin coding the website.

**Comment by Alinoureddine1** [comment]
Figma designs were created and added to the sprint 1 file
