### ISSUE TITLE
User Story 12: Report Bug Feature

### ISSUE THREAD

**Issue by laurenrigante** [F4KER-X/TalentVault-SOEN-341-Project-2023#80]
As a user of the system (Both recruiter and applicant), I want to be able to report when I encounter a bug, so that my user experience may be improved.

Tasks
[Design UI of report bug page](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/85)
[Implement Functionality](https://github.com/F4KER-X/TalentVault-SOEN-341-Project-2023/issues/86)

**Comment by despinakouli** [comment]
AT - 12.1 Reporting a Bug

**User Acceptance Flow**

1. User (applicant and recruiter) goes to the footer and clicks on "Report Bug"
2. User is sent to a page with a form where they fill out information about the bug such as a description of the bug, the user's email and an attachment (screenshot).
3. User submits the bug and its sent to the developers
